---
title: "rWorkshop - Creating Graphs in R"
author: "Will Mckenna"
date: "8.3.2023"
output: html_document
---
#plots with ggplot2

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
```

```{r readData, include= FALSE}

ca_np <- read_csv(here("data","ca_np.csv"))
ci_np <- read_excel(here("data", "ci_np.xlsx"))

```

```{r graph, include = FALSE}

gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))
gg_base + geom_line( color = "purple", linetype = "dashed")
gg_base + geom_point(aes(size = visitors, color = visitors, alpha = 0.5))
gg_base + geom_col()

```
```{r, include = FALSE}

gg_base + geom_col(aes(fill = visitors)) + theme_minimal() + labs(
  x = "Year",
  y = "Annual Park Visitors",
  title = "Channel Islands NP Visitation",
  subtitle = "(1963 - 2016)"
)

```
```{r multi-series, include = FALSE}
gg_np <- ggplot(data = ca_np, aes(x=year, y = visitors, group = park_name)) + geom_line()

##split up the graph into multiple panels

gg_np + 
  geom_line(show.legend = FALSE) + 
  theme_light() +
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)

```

